version: '3.7'

services:
  graphql-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-challenge
    depends_on:
      - mongo-db
    networks:
      - app-connect
    ports:
      - '3333:3333'
    volumes:
      - ./src:/app/src

  mongo-db:
    container_name: mongo-db
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - mongo-db-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-connect

volumes:
  mongo-db-data:

networks:
  app-connect:
    driver: bridge
