version: '3.7'

services:
  mongo-db:
    container_name: mongo-db
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - mongo-db-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-connect

volumes:
  mongo-db-data:

networks:
  app-connect:
    driver: bridge
